name: Build Executable

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, centos-8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies for CentOS
      if: matrix.os == 'centos-8'
      run: |
        sudo yum install -y gcc python3 python3-devel
        python3 -m pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed SortingApp.py

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/*
