name: Build Executable for Multiple Platforms

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # Set up Python for Ubuntu, macOS, and Windows
    - name: Set up Python (Ubuntu/macOS/Windows)
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies on Ubuntu
    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxkbcommon-x11-0 \
          libxcb-shape0 \
          libxcb-xfixes0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-render-util0 \
          libxcb-cursor0 \
          libxcb-xkb1 \
          libxcb-randr0 \
          libxkbcommon0 \
          libxcb-render0 \
          libxrender1 \
          libgl1-mesa-glx \
          build-essential \
          qtbase5-dev \
          qtchooser \
          qt5-qmake \
          qtbase5-dev-tools

    # Install dependencies for macOS and Windows using requirements.txt
    - name: Install dependencies (Ubuntu/macOS/Windows)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build with PyInstaller for Ubuntu, macOS, and Windows
    - name: Build with PyInstaller (Ubuntu/macOS/Windows)
      run: |
        pyinstaller --onefile --windowed SortingApp.py

    # Windows-specific step to include the icon
    - name: Build with PyInstaller for Windows (with icon)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --windowed --icon=resources/sorticon.ico SortingApp.py

    # macOS-specific step to set executable permissions and zip the .app bundle
    - name: Set permissions and zip .app for macOS
      if: matrix.os == 'macos-latest'
      run: |
        chmod +x dist/SortingApp.app/Contents/MacOS/SortingApp
        cd dist
        zip -r SortingApp-macOS.zip SortingApp.app

    # Upload the native Ubuntu/macOS/Windows builds
    - name: Upload executable (Native Builds)
      uses: actions/upload-artifact@v3
      with:
        name: executable-${{ matrix.os }}
        path: |
          dist/*

    # Additional step: Build for Rocky Linux-compatible (via Docker) on Ubuntu
    - name: Build for Rocky Linux-compatible (via Docker)
      if: matrix.os == 'ubuntu-latest'
      run: |
        docker run --rm -v ${{ github.workspace }}:/src -w /src rockylinux:8 \
        bash -c "dnf install -y epel-release && \
                dnf install -y mesa-libGL-devel python3 python3-devel gcc zlib-devel kde-qt6-sdk && \
                python3 -m pip install wheel && \
                python3 -m pip install --upgrade pip setuptools && \
                python3 -m pip install --user --no-binary :all: PyQt6 && \
                python3 -m pip install -r requirements.txt && \
                pyinstaller --onefile --windowed SortingApp.py"

    # Upload the Red Hat-compatible build
    - name: Upload Red Hat-compatible executable
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: executable-redhat
        path: dist/*
